spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vivuxe
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        page-parameter: pageNumber
        size-parameter: size
      sort:
        sort-parameter: sort